variables:
  IMAGE_NAME: thanhben03/2hand-frontend-cicd
  IMAGE_TAG: react-app-dev-1.0

stages:
  - build
  - dockerize
  - deploy

build_react:
  stage: build
  image: node:18
  cache:
    paths:
      - node_modules/
  before_script:
    - export REACT_APP_API_URL=$REACT_APP_API_URL
  script:
    - npm ci
    - CI=false npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 hour
  only:
    - main

dockerize:
  stage: dockerize
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHA .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
  dependencies:
    - build_react
  only:
    - main

deploy_demo:
  stage: deploy
  variables:
    PORT: 81
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -p 22 -o StrictHostKeyChecking=no -i $SSH_KEY root@103.179.191.70 "
        docker ps -q --filter 'publish=$PORT' | xargs -r docker stop &&
        docker ps -aq --filter 'publish=$PORT' | xargs -r docker rm &&
        docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
        docker run -d -p $PORT:80 $IMAGE_NAME:$CI_COMMIT_SHA"
  only:
    - main
